# Numpy library

In [5]:
import numpy as np

In [6]:
my_list = [1,2,3,4]

In [7]:
my_list

[1, 2, 3, 4]

In [8]:
my_list2 = [5,4,3,2,1]
my_list2

[5, 4, 3, 2, 1]

In [9]:
# Float array

In [10]:
a = np.array([1,2,3])

In [11]:
a

array([1, 2, 3])

In [12]:
b= np.array([1.0,2.0,3.0])

In [13]:
b

array([1., 2., 3.])

In [15]:
b= np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])

In [17]:
matrix =[[1,2,3],[4,5,6],[7,8,9]]
matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
a = np.array([1,2,3])
a.ndim

1

In [21]:
b= np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
b.shape

(2, 3)

In [22]:
b.itemsize

8

In [23]:
b.size

6

In [24]:
c = np.array([[True, False],[False, True]])
c

array([[ True, False],
       [False,  True]])

In [25]:
a = np.array([1,2,3],dtype='int32')

In [26]:
a

array([1, 2, 3])

In [28]:
b= np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
b.dtype

dtype('float64')

In [29]:
#Random values:
np.random.rand(3)

array([0.98170614, 0.19766385, 0.16507651])

In [30]:
np.random.rand(3,5)

array([[0.66342258, 0.22943044, 0.27994842, 0.60903476, 0.68401202],
       [0.81541573, 0.13133236, 0.91693214, 0.27765826, 0.41986019],
       [0.39975248, 0.36505485, 0.53255073, 0.0567341 , 0.8906926 ]])

In [31]:
np.random.randn(4,3)


array([[ 1.38222381, -0.39116862,  2.44418829],
       [-1.74125256, -1.09346705,  0.19143777],
       [ 0.75801705,  0.66858629, -0.79691369],
       [-1.43783385,  0.33147821, -0.23654883]])

In [32]:
np.random.randint(2,100)

46

In [36]:
np.random.randint(-4,8, size=(3,3))

array([[ 4,  2,  2],
       [ 2,  0, -4],
       [ 1,  3,  3]])

In [37]:
np.random.randint(1,10,8)

array([3, 1, 3, 8, 3, 1, 8, 8])

In [39]:
# Numpy Data types
import pandas as pd
dtypes = pd.DataFrame(
    {
        'Type': ['int8', 'uint8', 'int16', 'uint16', 'int32', 'uint32', 'int64', 'uint64', 'float16', 'float32', 'float64', 'float128', 'complex64', 'complex128', 'bool', 'object', 'string_', 'unicode_'],
        'Type Code': ['i1', 'u1', 'i2', 'u2', 'i4', 'u4', 'i8', 'u8', 'f2', 'f4 or f', 'f8 or d', 'f16 or g', 'c8', 'c16', '', 'O', 'S', 'U']
    }
)
dtypes

Type Type Code
0         int8        i1
1        uint8        u1
2        int16        i2
3       uint16        u2
4        int32        i4
5       uint32        u4
6        int64        i8
7       uint64        u8
8      float16        f2
9      float32   f4 or f
10     float64   f8 or d
11    float128  f16 or g
12   complex64        c8
13  complex128       c16
14        bool          
15      object         O
16     string_         S
17    unicode_         U

In [41]:
# Create an array with specified data type
arr = np.array([1,2,3], dtype = 'f4')
print(arr)

[1. 2. 3.]


In [42]:
# create an array of evenly spaced numbers
arr = np.arange(0,20, 2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [43]:
#create an array of evenly space with eqqual interval
arr = np.linspace(0,10,20)

In [44]:
arr


array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [45]:
arr = np.linspace(0,100,20)

In [46]:
arr

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [48]:
#Create an array of random values in a given shape
np.random.rand(3,3)

array([[0.3753143 , 0.23423102, 0.44779456],
       [0.83544969, 0.99686847, 0.38509956],
       [0.8151283 , 0.42022165, 0.77317353]])

In [50]:
# create an array of zeros 
np.zeros((2,3), dtype='i4')

array([[0, 0, 0],
       [0, 0, 0]])

In [51]:
# create an array of ones
np.ones((2,3), dtype='i4')

array([[1, 1, 1],
       [1, 1, 1]])

In [52]:
#create an array of arbitary values
np.empty_like(arr)

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [53]:
#create an array for constant values
np.full((2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

In [59]:
#create an array with by repeting the values
arr = np.repeat(0,3)
arr

array([0, 0, 0])

In [60]:
#Mathematical Functions
arr = np.random.rand(5,5)

In [61]:
print(arr + 10)
print(arr - 10)
print(arr / 10)
print(arr * 10)

[[10.78746158 10.72082416 10.27069201 10.96690841 10.80337051]
 [10.79802105 10.58657835 10.79382807 10.02683085 10.06605868]
 [10.77423896 10.57792833 10.62342365 10.39939634 10.65671174]
 [10.81223869 10.31248811 10.83970355 10.72964386 10.07228746]
 [10.27531278 10.32741117 10.16309789 10.20399492 10.5231952 ]]
[[-9.21253842 -9.27917584 -9.72930799 -9.03309159 -9.19662949]
 [-9.20197895 -9.41342165 -9.20617193 -9.97316915 -9.93394132]
 [-9.22576104 -9.42207167 -9.37657635 -9.60060366 -9.34328826]
 [-9.18776131 -9.68751189 -9.16029645 -9.27035614 -9.92771254]
 [-9.72468722 -9.67258883 -9.83690211 -9.79600508 -9.4768048 ]]
[[0.07874616 0.07208242 0.0270692  0.09669084 0.08033705]
 [0.07980211 0.05865783 0.07938281 0.00268308 0.00660587]
 [0.0774239  0.05779283 0.06234236 0.03993963 0.06567117]
 [0.08122387 0.03124881 0.08397036 0.07296439 0.00722875]
 [0.02753128 0.03274112 0.01630979 0.02039949 0.05231952]]
[[7.87461579 7.20824159 2.70692014 9.66908407 8.03370508]
 [7.98021054 5.8657

In [62]:
#Exponential
np.exp(arr)

array([[2.19781037, 2.05612709, 1.31087128, 2.6298016 , 2.23305479],
       [2.22114106, 1.79782634, 2.21184734, 1.02719404, 1.0682894 ],
       [2.16894084, 1.78234218, 1.86530326, 1.49092441, 1.92844069],
       [2.252946  , 1.36682168, 2.3156804 , 2.07434173, 1.07496431],
       [1.31694253, 1.3873718 , 1.17715192, 1.22629193, 1.68741066]])

In [63]:
#Logarithmic
np.log(arr)

array([[-0.2389407 , -0.32736006, -1.30677358, -0.03365151, -0.21893927],
       [-0.2256203 , -0.53344904, -0.23088838, -3.61820297, -2.7172119 ],
       [-0.25587472, -0.54830541, -0.47252898, -0.91780102, -0.4205101 ],
       [-0.20796102, -1.16318887, -0.17470636, -0.31519872, -2.62710462],
       [-1.28984744, -1.11653851, -1.81340469, -1.58966017, -0.64780065]])

In [64]:
#Squareroot
np.sqrt(arr)

array([[0.88739032, 0.84901364, 0.52028071, 0.98331501, 0.89630938],
       [0.89332024, 0.76588403, 0.8909703 , 0.16380125, 0.25701882],
       [0.87990849, 0.76021598, 0.78957181, 0.63197812, 0.81037753],
       [0.90124286, 0.55900636, 0.9163534 , 0.85419194, 0.26886327],
       [0.52470257, 0.57219854, 0.4038538 , 0.45165797, 0.72332234]])

In [65]:
#Sine values
np.sin(arr)

array([[0.70856433, 0.66000406, 0.26739832, 0.8231341 , 0.71970027],
       [0.71597594, 0.55351458, 0.71304243, 0.02682763, 0.06601064],
       [0.69917217, 0.54628989, 0.58381818, 0.38886226, 0.61051584],
       [0.72582893, 0.3074272 , 0.74444522, 0.66660421, 0.07222452],
       [0.27184795, 0.3215928 , 0.16237576, 0.20258303, 0.49965045]])

In [66]:
np.cos(arr)

array([[0.70564622, 0.75126204, 0.96358608, 0.56784704, 0.6942849 ],
       [0.69812495, 0.83283949, 0.70112088, 0.99964007, 0.99781892],
       [0.71495334, 0.83759618, 0.81188443, 0.9212959 , 0.79200404],
       [0.68787525, 0.9515716 , 0.66768354, 0.74541185, 0.9973884 ],
       [0.96234022, 0.94687807, 0.986729  , 0.97926509, 0.86622712]])

In [67]:
np.sum(arr, axis=0)

array([3.44727307, 2.52523011, 2.69074518, 2.32677438, 2.12162359])

In [68]:
np.sum(arr, axis=1)

array([3.54925667, 2.27131699, 3.03169902, 2.76636168, 1.49301197])

In [70]:
np.argmax(arr, axis=0)
np.argmin(arr, axis=0)

array([4, 3, 4, 1, 1], dtype=int64)

In [71]:
np.argmax(arr, axis=1)
np.argmin(arr, axis=1)

array([2, 3, 3, 4, 2], dtype=int64)

In [ ]:
#Basic Information:Pandas

In [102]:
import pandas as pd

In [103]:
data1 = {
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny']
}

In [104]:
df = pd.DataFrame(data1)
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [105]:
df.shape

(6, 4)

In [106]:
df.head()

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [107]:
df.tail(3)

day  temperature  windspeed  event
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [108]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [109]:
#Identify the max temperature

df['temperature'].max()

35

In [110]:
#Identify the temparature >32
df[df['temperature']>32]

day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [111]:
#Identify the date having highest temperature
df['day'][df['temperature'] == df['temperature'].max()]

1    1/2/2017
Name: day, dtype: object

In [112]:
df.set_index('day')

temperature  windspeed  event
day                                    
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [113]:
df.set_index('day', inplace=True)

In [114]:
df

temperature  windspeed  event
day                                    
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [115]:
df.index

Index(['1/1/2017', '1/2/2017', '1/3/2017', '1/4/2017', '1/5/2017', '1/6/2017'], dtype='object', name='day')

In [116]:
df.loc['1/5/2017']

temperature      32
windspeed         4
event          Rain
Name: 1/5/2017, dtype: object